name: Sample Pipeline

on:
    push:
    workflow_dispatch: 

jobs:
    build-on-server:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ["3.8", "3.9", "3.11"]  
            fail-fast: false
            max-parallel: 1
        steps:
            - uses: actions/checkout@v4
            - name: Setup Python
              uses: actions/setup-python@v3
              with: 
                python-version: ${{ matrix.python-version }}
            - name: Install pip 
              timeout-minutes: 10
              run: |
                python -m pip install --upgrade pip 
                pip --version 
            - name: Install dependencies 
              run: |
                pip install -r requirements.txt
                pip list 

    build-on-docker:
        needs: build-on-server
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ["3.8", "3.9", "3.11"]
            fail-fast: false
            max-parallel: 2
        steps:
            - name: Check if docker exists 
              run: |
                docker --version
            - name: Create Docker image
              run: |
                docker build -t my-app:${{ matrix.python-version }} --build-arg PYTHON-VERSION=${{ matrix.python-version }} .
                docker images 

            

        