name: Sample Pipeline

on:
    push:
    # workflow_dispatch: 

jobs:
    build-on-docker:
        if: github.ref == 'ref/heads/develop'
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ["3.8", "3.9", "3.11"]
            fail-fast: false
            max-parallel: 2
        steps:
            - uses: actions/checkout@v4
            - name: Check if docker exists 
              run: |
                docker --version
            - name: Create Docker image
              run: |
                docker build -t my-app:${{ matrix.python-version }} --build-arg PYTHON_VERSION=${{ matrix.python-version }} .
                docker images 
            - name: Run docker container
              run: |
                docker run -itd -p 8501:8501 my-app:${{ matrix.python-version}}
                docker ps 
                wget localhost:8501
                ls 
           

        
